sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ak47ak74
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDuFKGQ9mG97X5UcH2n
    access-key-secret: 8jvSSO0zdG3v5xs5BMp2dHVCNjK1t8
    bucket-name: sky-waimaitest
